baseURL = 'https://mdm508.github.io'
languageCode = 'en-us'
title = 'Coding With Matt'
theme = 'hugo-xmin'

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

custom_css = ["custom.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1 

[[menu.main]]
name = "Posts"
url = "/post/"
weight = 2


[[menu.main]]
name = "Swift"
url = "/swiftnote/"
weight = 4

[[menu.main]]
name = "Draw"
url = "/draw/"
weight = 5

